# Generated by Django 5.1.5 on 2026-01-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('REFERRAL_BONUS', 'Referral Bonus'), ('BINARY_PAIR', 'Binary Pair'), ('BINARY_PAIR_COMMISSION', 'Binary Pair Commission'), ('DIRECT_USER_COMMISSION', 'Direct User Commission'), ('TDS_DEDUCTION', 'TDS Deduction'), ('EMI_DEDUCTION', 'EMI Deduction'), ('RESERVE_DEDUCTION', 'Reserve Deduction'), ('PAYOUT', 'Payout'), ('DEPOSIT', 'Deposit'), ('REFUND', 'Refund')], max_length=25),
        ),
    ]
