# Generated by Django 5.1.5 on 2026-01-27 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_status'),
        ('wallet', '0004_alter_wallettransaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The activation_amount withheld from cancelled booking', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('redeemed', 'Redeemed'), ('expired', 'Expired')], default='pending', help_text='Status of activation points', max_length=20)),
                ('redeemable_after', models.DateTimeField(help_text='Date and time when points can be redeemed (1 year from cancellation)')),
                ('redeemed_at', models.DateTimeField(blank=True, help_text='Date and time when points were redeemed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Booking from which activation_amount was withheld', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_points', to='booking.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activation Points',
                'verbose_name_plural': 'Activation Points',
                'db_table': 'activation_points',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'redeemable_after'], name='activation__user_id_09cc24_idx')],
            },
        ),
    ]
