# Generated by Django 5.1.5 on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_add_active_buyer_bonus_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='credited_while_non_active_buyer',
            field=models.BooleanField(
                default=False,
                help_text="True if this commission was credited when user was not an Active Buyer (counts toward max_commission_before_active_buyer_amount cap)."
            ),
        ),
    ]
