# Generated by Django 5.1.5 on 2026-01-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of vehicle features'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary of vehicle specifications (key-value pairs)'),
        ),
    ]
