# Generated by Django 5.1.5 on 2026-01-08 05:11

from django.db import migrations, models


def convert_null_to_defaults(apps, schema_editor):
    """Convert any NULL values to empty list/dict"""
    Vehicle = apps.get_model('inventory', 'Vehicle')
    # Update any vehicles with NULL features to empty list
    Vehicle.objects.filter(features__isnull=True).update(features=[])
    # Update any vehicles with NULL specifications to empty dict
    Vehicle.objects.filter(specifications__isnull=True).update(specifications={})


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_vehicle_features_vehicle_specifications'),
    ]

    operations = [
        # First, convert any NULL values to defaults
        migrations.RunPython(convert_null_to_defaults, migrations.RunPython.noop),
        # Then alter the fields to not allow NULL
        migrations.AlterField(
            model_name='vehicle',
            name='features',
            field=models.JSONField(blank=True, default=list, null=False, help_text='List of vehicle features (optional, unlimited items)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, null=False, help_text='Dictionary of vehicle specifications - any key-value pairs (optional, unlimited items)'),
        ),
    ]
