# Generated by Django 5.1.5 on 2026-01-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_vehicleimage_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='model_code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
