# Generated by Django 5.1.5 on 2026-01-08 12:00

from django.db import migrations, models
import json


def default_vehicle_color():
    """Return default vehicle color array"""
    return ["white"]


def convert_vehicle_color_to_array(apps, schema_editor):
    """Convert existing vehicle_color values to JSONField array format"""
    Vehicle = apps.get_model('inventory', 'Vehicle')
    # Set all existing vehicles to default ["white"] as per user preference
    # Handle both string (old format) and list (new format) values
    for vehicle in Vehicle.objects.all():
        # If it's already a list, ensure it's ["white"]
        # If it's a string (from old CharField), convert to ["white"]
        vehicle.vehicle_color = ["white"]
        vehicle.save(update_fields=['vehicle_color'])


def reverse_convert_vehicle_color(apps, schema_editor):
    """Reverse migration: convert array back to string (use first color)"""
    Vehicle = apps.get_model('inventory', 'Vehicle')
    # Note: This runs before AlterField reverses, so field is still JSONField
    # We'll extract the first color from the array
    for vehicle in Vehicle.objects.all():
        if isinstance(vehicle.vehicle_color, list) and len(vehicle.vehicle_color) > 0:
            # Store first color - will be converted to CharField by AlterField reverse
            first_color = vehicle.vehicle_color[0] if vehicle.vehicle_color[0] else "white"
        else:
            first_color = "white"
        # Store as string in JSONField (will be converted properly when field reverses)
        vehicle.vehicle_color = first_color
        vehicle.save(update_fields=['vehicle_color'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_vehicle_model_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_color',
            field=models.JSONField(
                default=default_vehicle_color,
                help_text='List of available vehicle colors (default: ["white"])'
            ),
        ),
        migrations.RunPython(
            convert_vehicle_color_to_array,
            reverse_convert_vehicle_color
        ),
    ]

