# Generated by Django 5.1.5 on 2026-01-08 09:26

import core.inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_vehicle_vehicle_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_color',
            field=models.JSONField(blank=True, default=core.inventory.models.default_vehicle_color, help_text='List of available vehicle colors (default: ["white"])'),
        ),
    ]
