# Generated by Django 5.1.5 on 2026-01-08 12:00

from django.db import migrations, models
import json


def convert_battery_variant_before_field_change(apps, schema_editor):
    """Convert existing battery_variant CharField string values to JSON strings BEFORE field type change"""
    Vehicle = apps.get_model('inventory', 'Vehicle')
    
    # Get all vehicles with non-null battery_variant
    vehicles = Vehicle.objects.filter(battery_variant__isnull=False).exclude(battery_variant='')
    
    for vehicle in vehicles:
        battery_value = vehicle.battery_variant
        if battery_value:
            # Check if it's already a JSON string (starts with [)
            if isinstance(battery_value, str) and not battery_value.strip().startswith('['):
                # Convert single string to JSON array string
                battery_array_json = json.dumps([battery_value])
                # Update using model (this will work with CharField)
                Vehicle.objects.filter(id=vehicle.id).update(battery_variant=battery_array_json)


def convert_battery_variant_after_field_change(apps, schema_editor):
    """Ensure all battery_variant values are proper JSON arrays after field type change"""
    import json
    
    Vehicle = apps.get_model('inventory', 'Vehicle')
    
    # Get all vehicles with non-null battery_variant
    vehicles = Vehicle.objects.filter(battery_variant__isnull=False)
    
    for vehicle in vehicles:
        battery_value = vehicle.battery_variant
        
        # If it's a string, try to parse and convert
        if isinstance(battery_value, str):
            try:
                # Try to parse as JSON
                parsed = json.loads(battery_value)
                if not isinstance(parsed, list):
                    # Not a list, wrap it
                    battery_array = [battery_value]
                    Vehicle.objects.filter(id=vehicle.id).update(battery_variant=battery_array)
            except (json.JSONDecodeError, TypeError):
                # Not valid JSON, convert to array
                battery_array = [battery_value]
                Vehicle.objects.filter(id=vehicle.id).update(battery_variant=battery_array)
        elif not isinstance(battery_value, list):
            # Not a string or list, convert to array
            battery_array = [str(battery_value)]
            Vehicle.objects.filter(id=vehicle.id).update(battery_variant=battery_array)


def convert_battery_variant_to_string(apps, schema_editor):
    """Reverse migration: convert array back to string (take first element)"""
    Vehicle = apps.get_model('inventory', 'Vehicle')
    for vehicle in Vehicle.objects.all():
        if isinstance(vehicle.battery_variant, list) and len(vehicle.battery_variant) > 0:
            vehicle.battery_variant = vehicle.battery_variant[0]
            vehicle.save(update_fields=['battery_variant'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_vehicle_vehicle_color'),
    ]

    operations = [
        # First, convert string values to JSON strings (while field is still CharField)
        migrations.RunPython(convert_battery_variant_before_field_change, migrations.RunPython.noop),
        # Then, change the field type to JSONField
        migrations.AlterField(
            model_name='vehicle',
            name='battery_variant',
            field=models.JSONField(default=list, blank=True, help_text='List of battery variants (e.g., ["40kWh", "60kWh"])'),
        ),
        # Finally, ensure all values are proper JSON arrays
        migrations.RunPython(convert_battery_variant_after_field_change, convert_battery_variant_to_string),
    ]
