# Generated by Django 5.1.5 on 2026-01-14 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_vehicle_variant_and_more'),
        ('inventory', '0008_alter_vehicle_battery_variant_to_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.IntegerField(default=0, help_text='Total quantity of this vehicle')),
                ('available_quantity', models.IntegerField(default=0, help_text='Available quantity (not reserved)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Stock',
                'verbose_name_plural': 'Vehicle Stocks',
                'db_table': 'vehicle_stock',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Quantity reserved')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('released', 'Released'), ('completed', 'Completed')], default='reserved', help_text='Reservation status', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When reservation expires (null = never expires)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservation', to='booking.booking')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.vehicle')),
                ('vehicle_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.vehiclestock')),
            ],
            options={
                'verbose_name': 'Stock Reservation',
                'verbose_name_plural': 'Stock Reservations',
                'db_table': 'stock_reservations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='stock_reser_status_da6fe9_idx')],
            },
        ),
    ]
