# Generated by Django 4.2.7 on 2026-01-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('tds_certificate', 'TDS Certificate'), ('pan_card', 'PAN Card'), ('aadhaar', 'Aadhaar'), ('bank_statement', 'Bank Statement'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='compliance/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Compliance Document',
                'verbose_name_plural': 'Compliance Documents',
                'db_table': 'compliance_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TDSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=10)),
                ('total_payout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tds_deducted', models.DecimalField(decimal_places=2, max_digits=12)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='compliance/tds/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TDS Record',
                'verbose_name_plural': 'TDS Records',
                'db_table': 'tds_records',
                'ordering': ['-financial_year', '-created_at'],
            },
        ),
    ]
