# Generated by Django 4.2.7 on 2026-02-13 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('terms_conditions', 'Terms & Conditions'), ('legal_agreement', 'Legal Agreement'), ('policy', 'Policy'), ('other', 'Other')], default='other', max_length=50)),
                ('content', models.TextField(help_text='Document content/text')),
                ('file', models.FileField(blank=True, help_text='Optional PDF/document file attachment', null=True, upload_to='compliance/distributor_documents/')),
                ('version', models.CharField(default='1.0', help_text="Document version (e.g., '1.0', '2.0')", max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether document is currently active')),
                ('is_required', models.BooleanField(default=False, help_text='Whether acceptance is mandatory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When document becomes effective')),
                ('effective_until', models.DateTimeField(blank=True, help_text='When document expires (optional)', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_distributor_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distributor Document',
                'verbose_name_plural': 'Distributor Documents',
                'db_table': 'distributor_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistributorDocumentAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(help_text="User's IP address at acceptance", max_length=45)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/user agent info', null=True)),
                ('otp_verified', models.BooleanField(default=False, help_text='Whether OTP was verified')),
                ('otp_identifier', models.CharField(blank=True, help_text='Email/mobile used for OTP', max_length=255)),
                ('accepted_version', models.CharField(help_text='Document version at acceptance', max_length=20)),
                ('timeline_data', models.JSONField(blank=True, default=dict, help_text='Additional metadata/timeline info', null=True)),
                ('user_info_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of user info at acceptance', null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='compliance.distributordocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_document_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distributor Document Acceptance',
                'verbose_name_plural': 'Distributor Document Acceptances',
                'db_table': 'distributor_document_acceptances',
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['user', 'document'], name='distributor_user_id_61e953_idx'), models.Index(fields=['accepted_at'], name='distributor_accepte_3d0da7_idx'), models.Index(fields=['ip_address'], name='distributor_ip_addr_032287_idx')],
                'unique_together': {('user', 'document', 'accepted_version')},
            },
        ),
        migrations.AddIndex(
            model_name='distributordocument',
            index=models.Index(fields=['is_active', 'document_type'], name='distributor_is_acti_d8282f_idx'),
        ),
        migrations.AddIndex(
            model_name='distributordocument',
            index=models.Index(fields=['effective_from', 'effective_until'], name='distributor_effecti_8f8cbc_idx'),
        ),
    ]
