# Generated by Django 4.2.7 on 2026-02-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_distributordocument_distributordocumentacceptance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributordocument',
            name='document_type',
            field=models.CharField(choices=[('terms_conditions', 'Terms & Conditions'), ('legal_agreement', 'Legal Agreement'), ('policy', 'Policy'), ('payment_terms', 'Payment Terms'), ('distributor_terms', 'Distributor Terms'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
