# Generated by Django 4.2.7 on 2026-02-17 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_alter_distributordocument_document_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distributordocumentacceptance',
            unique_together=set(),
        ),
    ]
