# Generated by Django 4.2.7 on 2026-02-17 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0005_remove_unique_acceptance_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_terms_version', models.CharField(help_text='Payment Terms version that was accepted', max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now_add=True, help_text='Server timestamp in IST when accepted')),
                ('ip_address', models.CharField(help_text="User's IP address at acceptance", max_length=45)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/user agent info', null=True)),
                ('otp_verified', models.BooleanField(default=False, help_text='Whether OTP was verified')),
                ('otp_identifier', models.CharField(blank=True, help_text='Email/mobile used for OTP verification', max_length=255)),
                ('receipt_pdf_url', models.FileField(blank=True, help_text='Optional receipt/consent PDF (backend-generated only)', null=True, upload_to='compliance/payment_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Payment Acceptance',
                'verbose_name_plural': 'User Payment Acceptances',
                'db_table': 'user_payment_acceptances',
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAsaAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_version', models.CharField(help_text='ASA Terms version that was accepted', max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now_add=True, help_text='Server timestamp in IST when accepted')),
                ('ip_address', models.CharField(help_text="User's IP address at acceptance", max_length=45)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/user agent info', null=True)),
                ('otp_verified', models.BooleanField(default=False, help_text='Whether OTP was verified (always True for valid acceptances)')),
                ('otp_identifier', models.CharField(blank=True, help_text='Email/mobile used for OTP verification', max_length=255)),
                ('agreement_pdf_url', models.FileField(help_text='Generated agreement PDF (backend-generated only)', upload_to='compliance/asa_agreements/')),
                ('pdf_hash', models.CharField(help_text='SHA256 hash of the PDF for integrity verification', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asa_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User ASA Acceptance',
                'verbose_name_plural': 'User ASA Acceptances',
                'db_table': 'user_asa_acceptances',
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text="Version identifier (e.g., 'v1.0', 'v1.1')", max_length=20)),
                ('title', models.CharField(help_text='Title of the Payment Terms', max_length=200)),
                ('full_text', models.TextField(help_text='Full text content of the terms (HTML or Markdown supported)')),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When these terms become effective')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this version is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Terms',
                'verbose_name_plural': 'Payment Terms',
                'db_table': 'payment_terms',
                'ordering': ['-effective_from', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'effective_from'], name='payment_ter_is_acti_bb289c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AsaTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text="Version identifier (e.g., 'v1.0', 'v1.1')", max_length=20)),
                ('title', models.CharField(help_text='Title of the ASA Terms', max_length=200)),
                ('full_text', models.TextField(help_text='Full text content of the terms (HTML or Markdown supported)')),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When these terms become effective')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this version is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ASA Terms',
                'verbose_name_plural': 'ASA Terms',
                'db_table': 'asa_terms',
                'ordering': ['-effective_from', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'effective_from'], name='asa_terms_is_acti_982c3f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='asaterms',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_asa_terms'),
        ),
        migrations.AddIndex(
            model_name='userpaymentacceptance',
            index=models.Index(fields=['user', 'payment_terms_version'], name='user_paymen_user_id_ea5816_idx'),
        ),
        migrations.AddIndex(
            model_name='userpaymentacceptance',
            index=models.Index(fields=['accepted_at'], name='user_paymen_accepte_e28848_idx'),
        ),
        migrations.AddIndex(
            model_name='userpaymentacceptance',
            index=models.Index(fields=['ip_address'], name='user_paymen_ip_addr_eb5a60_idx'),
        ),
        migrations.AddIndex(
            model_name='userasaacceptance',
            index=models.Index(fields=['user', 'terms_version'], name='user_asa_ac_user_id_373a41_idx'),
        ),
        migrations.AddIndex(
            model_name='userasaacceptance',
            index=models.Index(fields=['accepted_at'], name='user_asa_ac_accepte_443932_idx'),
        ),
        migrations.AddIndex(
            model_name='userasaacceptance',
            index=models.Index(fields=['ip_address'], name='user_asa_ac_ip_addr_ba0d20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userasaacceptance',
            unique_together={('user', 'terms_version')},
        ),
    ]
