# Generated by Django 4.2.7 on 2026-02-22 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_userpaymentacceptance_userasaacceptance_paymentterms_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userasaacceptance',
            unique_together=set(),
        ),
    ]
