# Generated by Django 5.1.5 on 2026-02-02 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Member name or title', max_length=200)),
                ('image', models.ImageField(help_text='Member photo', upload_to='gallery/images/')),
                ('caption', models.TextField(blank=True, help_text='Description or bio')),
                ('level', models.CharField(choices=[('executive', 'Executive'), ('manager', 'Manager'), ('staff', 'Staff'), ('other', 'Other')], default='other', help_text='Member level/position category', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order within level (lower numbers appear first)')),
                ('status', models.BooleanField(default=True, help_text='Active/Inactive status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin/staff who added this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'db_table': 'gallery_items',
                'ordering': ['level', 'order', 'created_at'],
                'indexes': [models.Index(fields=['level', 'order'], name='gallery_ite_level_341138_idx'), models.Index(fields=['status'], name='gallery_ite_status_ec3e45_idx')],
            },
        ),
    ]
