# Generated by Django 5.1.5 on 2026-02-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='level',
            field=models.CharField(help_text='Member level/position category (any text)', max_length=100),
        ),
    ]
