# Generated by Django 5.1.5 on 2026-01-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_vehicle_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='referrer_was_distributor',
            field=models.BooleanField(default=False, help_text='Whether the referrer was a distributor when this booking was created'),
        ),
    ]
