# Generated by Django 5.1.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_referrer_was_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

