# Generated by Django 4.2.7 on 2026-02-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_receipt',
            field=models.FileField(blank=True, help_text='PDF receipt generated after booking payment', null=True, upload_to='booking_receipts/'),
        ),
    ]
