# Generated by Django 4.2.7 on 2026-02-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_deductions_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, help_text='PDF receipt generated after payment confirmation', null=True, upload_to='payment_receipts/'),
        ),
    ]
