# Generated by Django 5.1.5 on 2026-01-14 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reservation_timeout_minutes', models.IntegerField(blank=True, help_text='Booking reservation timeout in minutes. Set to null for never expires. Default: 1440 (24 hours)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated these settings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
                'db_table': 'platform_settings',
            },
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('settings', 'PlatformSettings').objects.get_or_create(
                pk=1,
                defaults={'booking_reservation_timeout_minutes': 1440}
            )[0],
            reverse_code=lambda apps, schema_editor: None,
        ),
    ]
