# Generated by Django 5.1.5 on 2026-01-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='binary_commission_activation_count',
            field=models.IntegerField(default=3, help_text='Number of direct users needed to activate binary commission (default: 3)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='binary_pair_commission_amount',
            field=models.DecimalField(decimal_places=2, default=2000, help_text='Commission amount per binary pair after activation (default: ₹2000)', max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='binary_tds_percentage',
            field=models.DecimalField(decimal_places=2, default=20, help_text='TDS percentage on binary pair commission after threshold (default: 20%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='binary_tds_threshold_pairs',
            field=models.IntegerField(default=5, help_text='Number of pairs after activation before TDS deduction starts (default: 5)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='direct_user_commission_amount',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Commission amount per direct user added before binary commission activation (default: ₹1000)', max_digits=10),
        ),
    ]
