# Generated by Django 5.1.5 on 2026-01-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_platformsettings_binary_commission_activation_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsettings',
            name='binary_tds_percentage',
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='binary_commission_tds_percentage',
            field=models.DecimalField(decimal_places=2, default=20, help_text='TDS percentage on ALL binary commissions - direct user and pairs (default: 20%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='binary_daily_pair_limit',
            field=models.IntegerField(default=10, help_text='Maximum binary pairs per day after activation (default: 10 pairs = ₹20,000)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='binary_extra_deduction_percentage',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Extra deduction percentage on binary pair commission for 6th+ pairs (default: 20%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='binary_tds_threshold_pairs',
            field=models.IntegerField(default=5, help_text='Number of pairs after activation before extra deduction starts (default: 5)'),
        ),
    ]
