# Generated by Django 5.1.5 on 2026-01-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_remove_platformsettings_binary_tds_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='binary_tree_default_placement_side',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', help_text='Default placement side for binary tree (left or right). Controls which side chain is followed after first 2 users.', max_length=5),
        ),
    ]
