# Generated by Django 5.1.5 on 2026-01-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_platformsettings_binary_tree_default_placement_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='distributor_application_auto_approve',
            field=models.BooleanField(default=True, help_text='If True, distributor applications are automatically approved upon submission. If False, applications require admin/staff approval.'),
        ),
    ]
