# Generated by Django 5.1.5 on 2026-01-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_add_distributor_application_auto_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='binary_commission_initial_bonus',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Initial bonus amount credited to user's wallet and total_earnings when binary commission is activated (3 persons). TDS is deducted from this amount, but TDS is NOT deducted from booking balance.", max_digits=10),
        ),
    ]
