# Generated by Django 5.1.5 on 2026-01-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_add_binary_commission_initial_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='payout_approval_needed',
            field=models.BooleanField(default=True, help_text='If True, payout requests require admin approval before processing. If False, payouts are automatically processed upon creation.'),
        ),
    ]
