# Generated by Django 5.1.5 on 2026-01-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_add_payout_approval_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='payout_tds_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='TDS percentage applied on payout withdrawals (default: 0, meaning no payout TDS)', max_digits=5),
        ),
    ]
