# Generated by Django 5.1.5 on 2026-01-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_platformsettings_activation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='activation_amount',
            field=models.DecimalField(decimal_places=2, default=5000, help_text='Minimum payment amount per booking required for seniors to earn commission. If payment is less than this amount, no commission is credited, but user is still counted in descendants calculation. On cancellation, this amount is withheld for future point redemption. (default: ₹5000)', max_digits=10),
        ),
    ]
