# Generated by Django 5.1.5 on 2026-01-27 05:58

from django.db import migrations


def update_activation_amount_default(apps, schema_editor):
    """Update existing PlatformSettings instance to have activation_amount = 5000"""
    PlatformSettings = apps.get_model('settings', 'PlatformSettings')
    settings = PlatformSettings.objects.filter(pk=1).first()
    if settings:
        settings.activation_amount = 5000
        settings.save(update_fields=['activation_amount'])


def reverse_update(apps, schema_editor):
    """Reverse migration - set activation_amount back to 0"""
    PlatformSettings = apps.get_model('settings', 'PlatformSettings')
    settings = PlatformSettings.objects.filter(pk=1).first()
    if settings:
        settings.activation_amount = 0
        settings.save(update_fields=['activation_amount'])


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_alter_platformsettings_activation_amount'),
    ]

    operations = [
        migrations.RunPython(update_activation_amount_default, reverse_update),
    ]
