# Generated by Django 5.1.5 on 2026-01-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_update_activation_amount_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='max_earnings_before_active_buyer',
            field=models.IntegerField(default=5, help_text='Maximum number of binary pairs non-Active Buyer distributors can earn commission for before becoming Active Buyer (default: 5 pairs). 6th+ pairs are blocked until user becomes Active Buyer.'),
        ),
    ]
