# Generated by Django 4.2.7 on 2026-02-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_add_max_earnings_before_active_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='company_referral_code',
            field=models.CharField(default='COMPANY', help_text="Static referral code representing the company (used for first booking in the system). Default: 'COMPANY'", max_length=20),
        ),
    ]
