# Generated by Django 4.2.7 on 2026-02-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_add_company_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='company_email',
            field=models.EmailField(default='inquire@dialight.mail', help_text='Company email for receipts and documents', max_length=254),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='company_name',
            field=models.CharField(default='ZUJA ELECTRICAL INNOVATION (P) LTD', help_text='Company name for receipts and documents', max_length=200),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='company_phone',
            field=models.CharField(default='222 555 7777', help_text='Company phone number for receipts and documents', max_length=20),
        ),
    ]
