# Generated by Django 4.2.7 on 2026-02-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_add_company_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='company_address',
            field=models.TextField(default='Kuttiyadiyil, Arrattuvazhy, Alappuzha North, Ambalapuzha A, Alappuzha – 688007, Kerala, India', help_text='Company address for receipts and documents'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='company_phone',
            field=models.CharField(default='+91 7356360777', help_text='Company phone number for receipts and documents', max_length=20),
        ),
    ]
