# Generated by Django 4.2.7 on 2026-02-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_add_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='company_address',
            field=models.TextField(default='Kuttiyadiyil, Arrattuvazhy, Alappuzha North, Ambalapuzha, Alappuzha – 688007, Kerala, India', help_text='Company address for receipts and documents'),
        ),
    ]
