# Generated by Django 5.1.5 on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_alter_platformsettings_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='max_commission_before_active_buyer_amount',
            field=models.DecimalField(
                decimal_places=2,
                default=10000,
                help_text="Maximum total commission (direct + binary + initial bonus) a non-Active Buyer can earn. Once reached, no further commission until user becomes Active Buyer. Partial credit allowed (e.g. at ₹9,900, next ₹1,000 credits only ₹100). Default: ₹10,000.",
                max_digits=10,
            ),
        ),
    ]
