# Generated by Django 4.2.7 on 2026-01-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pair_number', models.IntegerField()),
                ('emi_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Binary Earning',
                'verbose_name_plural': 'Binary Earnings',
                'db_table': 'binary_earnings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BinaryNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=5, null=True)),
                ('level', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('left_count', models.IntegerField(default=0)),
                ('right_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Binary Node',
                'verbose_name_plural': 'Binary Nodes',
                'db_table': 'binary_nodes',
            },
        ),
        migrations.CreateModel(
            name='BinaryPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earning_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('pair_month', models.IntegerField()),
                ('pair_year', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Binary Pair',
                'verbose_name_plural': 'Binary Pairs',
                'db_table': 'binary_pairs',
                'ordering': ['-created_at'],
            },
        ),
    ]
