# Generated by Django 4.2.7 on 2026-01-06 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('binary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binarypair',
            name='left_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_pairs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='binarypair',
            name='right_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_pairs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='binarypair',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binary_pairs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='binarynode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='binary.binarynode'),
        ),
        migrations.AddField(
            model_name='binarynode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='binary_node', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='binaryearning',
            name='binary_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='binary.binarypair'),
        ),
        migrations.AddField(
            model_name='binaryearning',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binary_earnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='binarypair',
            index=models.Index(fields=['user', 'pair_month', 'pair_year'], name='binary_pair_user_id_568af9_idx'),
        ),
    ]
