# Generated by Django 5.1.5 on 2026-01-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binarynode',
            name='binary_commission_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='binarynode',
            name='direct_children_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='binarypair',
            name='pair_number_after_activation',
            field=models.IntegerField(blank=True, help_text='Pair number after binary commission activation (null if before activation)', null=True),
        ),
    ]
