# Generated by Django 5.1.5 on 2026-01-16 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0003_binarynode_binary_commission_activated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='binarypair',
            name='extra_deduction_applied',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of extra deduction applied for 6th+ pairs (additional 20%)', max_digits=10),
        ),
        migrations.AddField(
            model_name='binarypair',
            name='is_carry_forward_pair',
            field=models.BooleanField(default=False, help_text='Whether this pair used carried-forward members from previous day'),
        ),
        migrations.AddField(
            model_name='binarypair',
            name='pair_date',
            field=models.DateField(blank=True, help_text='Date when pair was created (for daily limit tracking)', null=True),
        ),
        migrations.CreateModel(
            name='BinaryCarryForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carried_forward_date', models.DateField(help_text='Date when members were carried forward')),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], help_text='Side with long leg (more remaining members)', max_length=5)),
                ('initial_member_count', models.IntegerField(help_text='Total members carried forward from long leg')),
                ('matched_count', models.IntegerField(default=0, help_text='How many carried-forward members have been matched')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this carry-forward is still active')),
                ('matched_at', models.DateTimeField(blank=True, help_text='When last match occurred', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binary_carry_forwards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Binary Carry Forward',
                'verbose_name_plural': 'Binary Carry Forwards',
                'db_table': 'binary_carry_forwards',
                'ordering': ['-carried_forward_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='binarypair',
            name='carry_forward',
            field=models.ForeignKey(blank=True, help_text='Reference to carry-forward record if this pair used carried-forward members', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairs', to='binary.binarycarryforward'),
        ),
        migrations.AddIndex(
            model_name='binarycarryforward',
            index=models.Index(fields=['user', 'is_active', 'carried_forward_date'], name='binary_carr_user_id_4dff5e_idx'),
        ),
    ]
