# Generated by Django 5.1.5 on 2026-01-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0004_binarypair_extra_deduction_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='binarypair',
            name='blocked_reason',
            field=models.TextField(blank=True, help_text="Reason for blocking commission (e.g., 'Not Active Buyer, 6th+ pair')"),
        ),
        migrations.AddField(
            model_name='binarypair',
            name='commission_blocked',
            field=models.BooleanField(default=False, help_text='Whether commission was blocked due to Active Buyer requirement (6th+ pair for non-Active Buyer distributors)'),
        ),
    ]
