# Generated by Django 5.1.5 on 2026-01-19 03:40

from django.db import migrations, models


def backfill_activation_timestamp(apps, schema_editor):
    """
    Backfill activation_timestamp for existing nodes where binary_commission_activated = True
    Use updated_at as an approximation of when activation occurred
    """
    BinaryNode = apps.get_model('binary', 'BinaryNode')
    nodes_to_update = BinaryNode.objects.filter(
        binary_commission_activated=True,
        activation_timestamp__isnull=True
    )
    for node in nodes_to_update:
        node.activation_timestamp = node.updated_at
        node.save(update_fields=['activation_timestamp'])


def reverse_backfill(apps, schema_editor):
    """
    Reverse migration - set activation_timestamp to None
    """
    BinaryNode = apps.get_model('binary', 'BinaryNode')
    BinaryNode.objects.filter(binary_commission_activated=True).update(activation_timestamp=None)


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0006_add_unique_parent_side_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='binarynode',
            name='activation_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp when binary commission was activated for this user', null=True),
        ),
        migrations.RunPython(backfill_activation_timestamp, reverse_backfill),
    ]
