# Generated by Django 4.2.7 on 2026-01-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_line1_user_address_line2_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='bank_passbook',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/bank_passbook/'),
        ),
    ]

