# Generated by Django 5.1.5 on 2026-01-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_nominee_kyc_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
