# Generated by Django 5.1.5 on 2026-01-14 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_nominee_kyc_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('business_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('years_in_business', models.IntegerField(blank=True, null=True)),
                ('previous_distribution_experience', models.TextField(blank=True, null=True)),
                ('product_interest', models.TextField(blank=True, null=True)),
                ('reference_name', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('business_license', models.FileField(blank=True, null=True, upload_to='distributor/business_license/')),
                ('tax_documents', models.FileField(blank=True, null=True, upload_to='distributor/tax_documents/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_applications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distributor Application',
                'verbose_name_plural': 'Distributor Applications',
                'db_table': 'distributor_applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
