# Generated by Django 5.1.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_distributor_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorapplication',
            name='is_distributor_terms_and_conditions_accepted',
            field=models.BooleanField(default=False),
        ),
    ]

