# Generated by Django 5.1.5 on 2026-02-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pan_card',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]

