# Generated by Django 5.1.5 on 2026-01-30 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='CREATED', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='razorpay_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Razorpay Payment',
                'verbose_name_plural': 'Razorpay Payments',
                'db_table': 'razorpay_payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_id'], name='razorpay_pa_order_i_c1467a_idx'), models.Index(fields=['payment_id'], name='razorpay_pa_payment_4d22ca_idx'), models.Index(fields=['status'], name='razorpay_pa_status_384ef9_idx'), models.Index(fields=['user', 'status'], name='razorpay_pa_user_id_43f63b_idx')],
            },
        ),
    ]
