# Generated by Django 5.1.5 on 2026-02-03 11:05

from django.db import migrations, models
from django.db.models import Count


def cleanup_duplicate_payment_ids(apps, schema_editor):
    """
    Clean up duplicate Payment records with the same payment_id.
    Keeps the latest Payment record for each payment_id and deletes older duplicates.
    """
    Payment = apps.get_model('payments', 'Payment')
    
    # Find all payment_ids that have duplicates
    duplicates = (
        Payment.objects
        .exclude(payment_id__isnull=True)
        .exclude(payment_id='')
        .values('payment_id')
        .annotate(count=Count('payment_id'))
        .filter(count__gt=1)
    )
    
    if not duplicates:
        return
    
    # For each duplicate payment_id, keep the latest and delete the rest
    for dup in duplicates:
        payment_id = dup['payment_id']
        payments = Payment.objects.filter(payment_id=payment_id).order_by('-created_at')
        
        # Keep the first (latest) one, delete the rest
        if payments.count() > 1:
            to_delete = payments[1:]  # All except the first (latest)
            for payment in to_delete:
                payment.delete()


def reverse_cleanup(apps, schema_editor):
    """Reverse migration - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        # First, clean up any duplicate payment_ids
        migrations.RunPython(cleanup_duplicate_payment_ids, reverse_cleanup),
        # Then, add the unique constraint
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
