# Generated by Django 5.1.5 on 2026-02-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_unique_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text='Razorpay event ID', max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, help_text='Event type (e.g., payment.captured)', max_length=100)),
                ('payload', models.JSONField(help_text='Full webhook payload')),
                ('processed', models.BooleanField(db_index=True, default=False, help_text='Whether event was successfully processed')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When event was processed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'db_table': 'webhook_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_id'], name='webhook_eve_event_i_bb7559_idx'), models.Index(fields=['event_type', 'processed'], name='webhook_eve_event_t_f5eefa_idx'), models.Index(fields=['created_at'], name='webhook_eve_created_8fa52f_idx')],
            },
        ),
    ]
