# Generated by Django 4.2.7 on 2026-02-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_add_razorpay_charges_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'content_type', 'object_id', 'status', 'created_at'], name='payment_order_reuse_idx'),
        ),
    ]
