# Generated by Django 5.1.5 on 2026-01-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='reason',
            field=models.TextField(blank=True, help_text="User's reason for payout request"),
        ),
    ]
