# Generated by Django 5.1.5 on 2026-02-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0003_add_reason_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text='Razorpay event ID', max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, help_text='Event type: payout.processed, payout.failed, fund_account.verified', max_length=100)),
                ('payload', models.JSONField(help_text='Full webhook payload')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='received', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if processing failed')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When event was processed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payout Webhook Log',
                'verbose_name_plural': 'Payout Webhook Logs',
                'db_table': 'payout_webhook_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_id'], name='payout_webh_event_i_f7da66_idx'), models.Index(fields=['event_type', 'status'], name='payout_webh_event_t_494f13_idx'), models.Index(fields=['status', 'created_at'], name='payout_webh_status_5b9e69_idx')],
            },
        ),
    ]
