# Generated by Django 4.2.7 on 2026-02-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0004_payoutwebhooklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
